---
abstract: 'Extensions for printing text onto surfaces'
author:
  - 'Kartik Thakore <kthakore@cpan.org>'
build_requires:
  Alien::SDL: 1.3
  ExtUtils::CBuilder: 0
  SDL: 2.404
configure_requires:
  Alien::SDL: 1.3
  Module::Build: 0.36
  SDL: 2.404
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SDLx-TTF
provides:
  SDLx::TTF:
    file: lib/SDLx/TTF.pm
    version: 0.002
requires:
  Alien::SDL: 1.3
  SDL: 2.404
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
